exp_id: rvt
tasks: all
bs: 3 
num_workers: 4
epochs: 1 15
sample_distribution_mode: task_uniform
peract:
  lr: 5e-5 
  warmup_steps: 2000
  optimizer_type: lamb
  lr_cos_dec: True
  transform_augmentation_xyz: [0.125, 0.125, 0.125]
  transform_augmentation_rpy: [0.0, 0.0, 45.0]
rvt:
  place_with_mean: False


depth: 1
attn_dim: 512


ds_rate: 1.0 
adapter: []
model: "MVT_Resnet"
output_dim: 512

pretrain: ../pretrains/UnadaptedR3M.pt
overwriter_log_dir: runs/UnadaptedR3M2RLBench_yours

### python train.py --exp_cfg_path configs/unadaptedR3M.yaml --device 0,1,2,3,4,5,6,7

